title: "GANGA VAMSIK SANIPINIDI"
description: "Actively Seeking Opportunities as Data Scientist | Data Engineer | Data Analyst – Skilled in Python, SQL, ML & Cloud."
#remote_theme: pages-themes/hacker@v0.2.0
theme: jekyll-theme-hacker
url: "https://vamsi4040.github.io"
baseurl: "/Data-Science-Journey"







