title: "Ganga Vamsik Sanipinidi"
description: "architect of digital insight, rigorously transforming messy data into strategic narratives while winking at the absurdity of the numbers I tame."
remote_theme: pages-themes/hacker@v0.2.0

nav:
  - title: "About Me"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Blogs"
    url: /blogs/
