title: "Ganga Vamsik Sanipinidi Portfolio"
description: "Data Scientist | Predictive Analytics | Machine Learning"
# Ganga Vamsik Sanipinidi

**Data Scientist**  
Hartford, Connecticut, USA

[![LinkedIn Badge](https://img.shields.io/badge/LinkedIn-Connect-blue)](https://www.linkedin.com/in/YourLinkedInProfile)
[![GitHub Badge](https://img.shields.io/badge/GitHub-Follow-lightgrey)](https://github.com/YourUsername)
[![Email Badge](https://img.shields.io/badge/Email-Contact%20Me-orange)](mailto:gvsanipinidi@example.com)

remote_theme: pages-themes/hacker@v0.2.0

nav:
  - title: "About Me"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Blogs"
    url: /blogs/
