title: "Ganga Vamsik Sanipinidi Portfolio"
description: "Data Scientist | Predictive Analytics | Machine Learning"
remote_theme: pages-themes/hacker@v0.2.0

nav:
  - title: "About Me"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Blogs"
    url: /Data-Science-Journey/blogs/
